language: python

matrix:
    include:
        - os: linux
          python: 3.2
          env: TOXENV=py32
        - os: linux
          python: 3.3
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33
# install:
#     - ./.travis/install.sh
script: make test