version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./etc/img/nginx.Dockerfile
    volumes:
      - ./sites:/sites:rw
    ports:
      - 80:80
    depends_on:
      - "php56"  
      - "php71"  
      - "php72"  
  php56: 
    build:
      context: ./
      dockerfile: ./etc/img/php56.Dockerfile
    volumes:
      - ./var/cachegrind:/cachegrind:rw
      - ./sites:/sites:rw
      - ./mysql.sock:/mysql.sock:rw
    expose:
      - "9000"
  php71: 
    build:
      context: ./
      dockerfile: ./etc/img/php71.Dockerfile
    volumes:
      - ./var/cachegrind:/cachegrind:rw
      - ./sites:/sites:rw
      - ./mysql.sock:/mysql.sock:rw
    expose:
      - "9000"
  php72: 
    build:
      context: ./
      dockerfile: ./etc/img/php72.Dockerfile
    volumes:
      - ./sites:/sites:rw
      - ./mysql.sock:/mysql.sock:rw
    expose:
      - "9000"