version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./etc/img/nginx.Dockerfile
    volumes:
      - ${SITESDIR}:/sites:rw
    ports:
      - ${WEBPORT}:80
  php56: 
    build:
      context: ./
      dockerfile: ./etc/img/php56.Dockerfile
    volumes:
      - ${CACHEGRINDDIR}:/cachegrind:rw
      - ${SITESDIR}:/sites:rw
      - ${MYSQLSOCK}:/mysql.sock:rw
    expose:
      - "9000"
  php71: 
    build:
      context: ./
      dockerfile: ./etc/img/php71.Dockerfile
    volumes:
      - ${CACHEGRINDDIR}:/cachegrind:rw
      - ${SITESDIR}:/sites:rw
      - ${MYSQLSOCK}:/mysql.sock:rw
    expose:
      - "9000"
  php72: 
    build:
      context: ./
      dockerfile: ./etc/img/php72.Dockerfile
    volumes:
      - ${CACHEGRINDDIR}:/cachegrind:rw
      - ${SITESDIR}:/sites:rw
      - ${MYSQLSOCK}:/mysql.sock:rw
    expose:
      - "9000"