version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./img/nginx.Dockerfile
    # volumes:
    #   - ./sites:/sites:rw
    ports:
      - 8080:80
  php56: 
    build:
      context: ./
      dockerfile: ./img/php56.Dockerfile