version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./etc/nginx/:/etc/nginx/conf.d/
      - ./sites:/sites
    ports:
      - "8080:80"
  php56: 
    build: img/php56.Dockerfile   