version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./etc/img/nginx.Dockerfile
    volumes:
      - ${SITESDIR}:/sites:rw
    ports:
      - ${WEBPORT}:80
  php56: 
    build:
      context: ./
      dockerfile: ./etc/img/php56.Dockerfile
    volumes:
      - ${CACHEGRINDDIR}:/cachegrind:rw
      - ${SITESDIR}:/sites:rw
      - ${MYSQLSOCK}:/mysql.sock:rw
    expose:
      - "9000"
  php71: 
    build:
      context: ./
      dockerfile: ./etc/img/php71.Dockerfile
    volumes:
      - ${CACHEGRINDDIR}:/cachegrind:rw
      - ${SITESDIR}:/sites:rw
      - ${MYSQLSOCK}:/mysql.sock:rw
    expose:
      - "9000"
  php72: 
    build:
      context: ./
      dockerfile: ./etc/img/php72.Dockerfile
    volumes:
      - ${CACHEGRINDDIR}:/cachegrind:rw
      - ${SITESDIR}:/sites:rw
      - ${MYSQLSOCK}:/mysql.sock:rw
    expose:
      - "9000"
  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes: 
  #       - ./var/mysql:/var/lib/mysql:rw
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'