version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./etc/img/nginx.Dockerfile
    volumes:
      - ./sites:/sites:rw
    ports:
      - 80:80
  php56: 
    build:
      context: ./
      dockerfile: ./etc/img/php56.Dockerfile
    volumes:
      - ./sites:/sites:rw
  php71: 
    build:
      context: ./
      dockerfile: ./etc/img/php71.Dockerfile
    volumes:
      - ./sites:/sites:rw