name: engine
base: docker 
version: '1.5.5'
summary: A nice and simple multi-tenant LEMP stack for web developers
description: |
  Engine is a Multi-tenanet LEMP stack that provides a powerful development 
  environment for building web applications. It provides sensisble defaults,
  the ability to use concurrent PHP versions, baked in mysql, vscode, and
  other niceites. Engine is written around docker, and is useful for 
  Magento 2 development.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  engine:
    source: .
  #  source: https://github.com/superterran/engine/archive/v1.5.5.tar.gz
    plugin: autotools
    install: |
      ls